# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.7150, 0.1641, 0.9911, 0.8237, 0.5583, 0.9884, 0.2826],
        [0.1516, 0.5002, 0.9511, 0.5639, 0.0425, 0.8533, 0.3583],
        [0.2667, 0.9568, 0.2328, 0.3545, 0.3816, 0.0921, 0.1341],
        [0.2290, 0.0662, 0.7236, 0.3698, 0.2376, 0.7572, 0.6738],
        [0.6488, 0.6771, 0.8277, 0.3574, 0.8824, 0.1778, 0.3398],
        [0.2858, 0.9082, 0.0530, 0.5581, 0.1021, 0.8103, 0.7334],
        [0.1902, 0.0301, 0.9704, 0.4831, 0.7081, 0.8935, 0.6930]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor1 = torch.rand(1,7).T
# Perform matrix multiplication
result = torch.matmul(tensor, tensor1)
result

tensor([[1.2858],
        [1.2270],
        [0.7956],
        [1.1735],
        [1.3740],
        [1.1483],
        [1.4459]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand(7,7)
torch.manual_seed(0)
tensor1 = torch.rand(1,7).T

# Matrix multiply tensors
result = torch.matmul(tensor,tensor1)
print(result)
print(result.shape)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [91]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU (augmentation code)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
with torch.cuda.device(0):
  tensor1 = torch.rand(2,3).cuda()
  tensor2 = torch.rand(2,3).cuda()
  print(tensor1)
  print(tensor2)
torch.device('cuda:1')

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


device(type='cuda', index=1)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [36]:
# Perform matmul on tensor_A and tensor_B
new_tensor = tensor2.T
result = torch.matmul(tensor1,new_tensor)
print(result)
print(result.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [44]:
# Find max
max = (result.max())
print(f'maximum:{max}')
# Find min
min = result.min()
print(f'minimum:{min}')


maximum:0.5617256760597229
minimum:0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [45]:
# Find arg max
max_index = result.argmax()
print(f'maximum index:{max_index}')
# Find arg min
min_index = result.argmin()
print(f'minimum index:{min_index}')


maximum index:3
minimum index:0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [65]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor1 = torch.rand(1,1,1,10)

# Remove single dimensions
tensor2 = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1,tensor1.shape)
print(tensor2,tensor2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
